/**
 * Pre-Request Hook: Inject Context
 *
 * Automatically enriches every Copilot prompt with project metadata:
 * - Current git branch and recent commits
 * - Project language and framework info
 * - Open file context hints
 *
 * Input (stdin):  JSON with { prompt, activeFile, ... }
 * Output (stdout): JSON with enriched prompt context
 */

import { execSync } from "node:child_process";

/**
 * Safely run a shell command and return trimmed output, or a fallback on failure.
 *
 * @param {string} cmd - Shell command to execute
 * @param {string} [fallback="unknown"] - Value to return if the command fails
 * @returns {string} Command output or fallback
 */
function safeExec(cmd, fallback = "unknown") {
  try {
    return execSync(cmd, { encoding: "utf-8", timeout: 5000 }).trim();
  } catch {
    return fallback;
  }
}

/**
 * Gather git metadata for the current repository.
 *
 * @returns {{ branch: string, recentCommits: string, status: string }}
 */
function getGitContext() {
  const branch = safeExec("git rev-parse --abbrev-ref HEAD");
  const recentCommits = safeExec(
    'git log --oneline -5 --no-decorate 2>/dev/null'
  );
  const status = safeExec("git diff --stat HEAD 2>/dev/null", "clean");

  return { branch, recentCommits, status };
}

/**
 * Detect project info from package.json or pom.xml in the workspace.
 *
 * @returns {{ language: string, framework: string, nodeVersion: string | null }}
 */
function getProjectContext() {
  const packageJson = safeExec("cat package.json 2>/dev/null", "");

  if (packageJson) {
    try {
      const pkg = JSON.parse(packageJson);
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      const framework = deps.express
        ? "Express"
        : deps.fastify
          ? "Fastify"
          : deps.next
            ? "Next.js"
            : "Node.js";

      return {
        language: "JavaScript/TypeScript",
        framework,
        nodeVersion: pkg.engines?.node ?? null,
      };
    } catch {
      // malformed package.json — fall through
    }
  }

  const pomExists = safeExec("test -f pom.xml && echo yes", "no");
  if (pomExists === "yes") {
    return {
      language: "Java",
      framework: "Spring Boot (Maven)",
      nodeVersion: null,
    };
  }

  return { language: "unknown", framework: "unknown", nodeVersion: null };
}

async function main() {
  // Read the incoming hook payload from stdin
  let input = "";
  for await (const chunk of process.stdin) {
    input += chunk;
  }

  const payload = JSON.parse(input);
  const git = getGitContext();
  const project = getProjectContext();

  // Build the enriched context block
  const contextBlock = [
    "--- Injected Project Context (auto-generated by pre-request hook) ---",
    `Git Branch: ${git.branch}`,
    `Recent Commits:\n${git.recentCommits}`,
    `Uncommitted Changes: ${git.status}`,
    `Language: ${project.language}`,
    `Framework: ${project.framework}`,
    "--- End Context ---",
  ].join("\n");

  // Append context to the original prompt
  const enrichedPayload = {
    ...payload,
    prompt: `${payload.prompt}\n\n${contextBlock}`,
  };

  // Write enriched payload to stdout for Copilot to consume
  process.stdout.write(JSON.stringify(enrichedPayload, null, 2));
}

main();
